on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Login to custom Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}
